### ISSUE TITLE
Crash when estimating large dataset

### ISSUE THREAD

**Issue by philippeauriach** [mapbox/mts-data-sync#14]
Hi,

I'm trying to estimate a (large) dataset. 
I validated the `.geojsonl` file using tilesets and it is displayed as valid, but when I run `mtsds --estimate` I get the following crash : 

```
TypeError: Cannot read property '1' of undefined
    at lineCover (/Users/philippeauriach/Development/OSS/mts-data-sync/node_modules/@mapbox/tile-cover/index.js:232:30)
    at polygonCover (/Users/philippeauriach/Development/OSS/mts-data-sync/node_modules/@mapbox/tile-cover/index.js:154:9)
    at getTiles (/Users/philippeauriach/Development/OSS/mts-data-sync/node_modules/@mapbox/tile-cover/index.js:79:9)
    at Proxy.exports.indexes (/Users/philippeauriach/Development/OSS/mts-data-sync/node_modules/@mapbox/tile-cover/index.js:53:12)
    at DestroyableTransform.<anonymous> (/Users/philippeauriach/Development/OSS/mts-data-sync/src/estimate.js:59:27)
    at DestroyableTransform.emit (node:events:376:20)
    at DestroyableTransform.EventEmitter.emit (node:domain:470:12)
    at addChunk (/Users/philippeauriach/Development/OSS/mts-data-sync/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/philippeauriach/Development/OSS/mts-data-sync/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/Users/philippeauriach/Development/OSS/mts-data-sync/node_modules/readable-stream/lib/_stream_readable.js:245:10)
```

It seems to come from the `@mapbox/tile-cover` package, but I have no idea what is the actual cause of this. 
I can provide my .geojsonl file if needed by email (2.5go)

Thanks

**Comment by jbranigan** [comment]
Hi @philippeauriach, happy to look into this. 
- How quickly in the process does this error get thrown?
- Have you tested it on a smaller subset of the data?

2.5GB is rather large for the capabilities of this tool. I've run it on 1GB of building footprint data and it took about 30 minutes with 16GB of RAM. One workaround would be to make the data smaller by covering it in a grid of points or running a concave hull. The area covered by tiles that intersect the data is the trick, so you can run through simpler data of the same geographic extent and get a valid cost estimate. 

If you want to share a sample of your data, maybe the first 500 lines or so, you can email me at john.branigan at mapbox.com.

**Comment by philippeauriach** [comment]
Hi @jbranigan ! This happens really fast in the process, and has been solved by modifying the following line : 

https://github.com/mapbox/tile-cover/blob/fecd2cfad1380e6e77600d0664f41b900eb1f290/index.js#L231

For: 
```
    if (ring && ring.length > 0 && y === ring[0][1]) ring.pop();
```

But I would love to understand what's causing the problem! 

Sending you a file (with only the first 100k lines) which does cause the error.

**Comment by jbranigan** [comment]
I think this is the cause: https://github.com/mapbox/tile-cover/issues/78

**Comment by philippeauriach** [comment]
I should have check, you're right! Sorry, and thank you for the help
